#!/usr/bin/env bash

if [ ! -d ${PWD}/venv ]; then
    echo "[requires python virtual environment.]"
    sudo apt-get install -y python3-venv
    echo "[CREATING VIRTUAL ENVIRONMENT]"
    python3 -m venv ./venv
    source ./venv/bin/activate
    pip install --upgrade pip;pip install Cython;pip install -r requirements.txt
    echo "Running Server. [CTRL-C to exit]"
    python server.py
else
    echo "Activating Virtual Environment."
    source ./venv/bin/activate
    echo "Running Server. [CTRL-C to exit]"
    python server.py
fi

